namespace SeaBattle
{
    partial class MainForm
    {
        /// <summary>
        /// Required constructor variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Release all used resources.
        /// </summary>
        /// <param name="disposing">true if the managed resource is to be disposed of; otherwise false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code automatically generated by Windows Form Designer

        /// <summary>
        /// Required method for constructor support - do not change
        /// contents of this method using the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            this.button4x = new System.Windows.Forms.Button();
            this.button3x = new System.Windows.Forms.Button();
            this.button2x = new System.Windows.Forms.Button();
            this.button1x = new System.Windows.Forms.Button();
            this.label2x = new System.Windows.Forms.Label();
            this.label3x = new System.Windows.Forms.Label();
            this.label4x = new System.Windows.Forms.Label();
            this.labelYourField = new System.Windows.Forms.Label();
            this.labelEnemyField = new System.Windows.Forms.Label();
            this.labelStatus = new System.Windows.Forms.Label();
            this.buttonRestart = new System.Windows.Forms.Button();
            this.labelComputerMove = new System.Windows.Forms.Label();
            this.label1x = new System.Windows.Forms.Label();
            this.contextMenuStrip = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.GameRestartToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ComputerMovesSpeedToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.SlowlyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.AverageToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.RapidlyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.InstantlyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.MarkComputerMovesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.buttonRotate = new System.Windows.Forms.Button();
            this.comboBoxComputerMoveSpeed = new System.Windows.Forms.ComboBox();
            this.buttonGameStart = new System.Windows.Forms.Button();
            this.labelShipsPlaceLeft = new System.Windows.Forms.Label();
            this.labelPlaceShips = new System.Windows.Forms.Label();
            this.progressBar = new System.Windows.Forms.ProgressBar();
            this.labelComputerMovingSpeed = new System.Windows.Forms.Label();
            this.labelShipPlacement = new System.Windows.Forms.Label();
            this.checkBoxMarkEnemyMoves = new System.Windows.Forms.CheckBox();
            this.panel = new System.Windows.Forms.Panel();
            this.groupBoxEnemy = new System.Windows.Forms.GroupBox();
            this.checkBoxEnemyRandomMoves = new System.Windows.Forms.CheckBox();
            this.buttonArrangeShipsRandomly = new System.Windows.Forms.Button();
            this.labelPrompt = new System.Windows.Forms.Label();
            this.contextMenuStrip.SuspendLayout();
            this.panel.SuspendLayout();
            this.groupBoxEnemy.SuspendLayout();
            this.SuspendLayout();
            // 
            // button4x
            // 
            this.button4x.Location = new System.Drawing.Point(462, 67);
            this.button4x.Name = "button4x";
            this.button4x.Size = new System.Drawing.Size(47, 23);
            this.button4x.TabIndex = 0;
            this.button4x.Text = "4x";
            this.button4x.UseVisualStyleBackColor = true;
            // 
            // button3x
            // 
            this.button3x.Location = new System.Drawing.Point(515, 67);
            this.button3x.Name = "button3x";
            this.button3x.Size = new System.Drawing.Size(47, 23);
            this.button3x.TabIndex = 1;
            this.button3x.Text = "3x";
            this.button3x.UseVisualStyleBackColor = true;
            // 
            // button2x
            // 
            this.button2x.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.button2x.Location = new System.Drawing.Point(568, 67);
            this.button2x.Name = "button2x";
            this.button2x.Size = new System.Drawing.Size(47, 23);
            this.button2x.TabIndex = 2;
            this.button2x.Text = "2x";
            this.button2x.UseVisualStyleBackColor = true;
            // 
            // button1x
            // 
            this.button1x.Location = new System.Drawing.Point(621, 67);
            this.button1x.Name = "button1x";
            this.button1x.Size = new System.Drawing.Size(47, 23);
            this.button1x.TabIndex = 3;
            this.button1x.Text = "1x";
            this.button1x.UseVisualStyleBackColor = true;
            // 
            // label2x
            // 
            this.label2x.AutoSize = true;
            this.label2x.Location = new System.Drawing.Point(586, 102);
            this.label2x.Name = "label2x";
            this.label2x.Size = new System.Drawing.Size(13, 13);
            this.label2x.TabIndex = 5;
            this.label2x.Text = "3";
            // 
            // label3x
            // 
            this.label3x.AutoSize = true;
            this.label3x.Location = new System.Drawing.Point(532, 102);
            this.label3x.Name = "label3x";
            this.label3x.Size = new System.Drawing.Size(13, 13);
            this.label3x.TabIndex = 6;
            this.label3x.Text = "2";
            // 
            // label4x
            // 
            this.label4x.AutoSize = true;
            this.label4x.Location = new System.Drawing.Point(477, 102);
            this.label4x.Name = "label4x";
            this.label4x.Size = new System.Drawing.Size(13, 13);
            this.label4x.TabIndex = 7;
            this.label4x.Text = "1";
            // 
            // labelYourField
            // 
            this.labelYourField.AutoSize = true;
            this.labelYourField.ForeColor = System.Drawing.Color.Green;
            this.labelYourField.Location = new System.Drawing.Point(154, 9);
            this.labelYourField.Name = "labelYourField";
            this.labelYourField.Size = new System.Drawing.Size(54, 13);
            this.labelYourField.TabIndex = 9;
            this.labelYourField.Text = "Your Field";
            // 
            // labelEnemyField
            // 
            this.labelEnemyField.AutoSize = true;
            this.labelEnemyField.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.labelEnemyField.Location = new System.Drawing.Point(535, 9);
            this.labelEnemyField.Name = "labelEnemyField";
            this.labelEnemyField.Size = new System.Drawing.Size(64, 13);
            this.labelEnemyField.TabIndex = 10;
            this.labelEnemyField.Text = "Enemy Field";
            this.labelEnemyField.Visible = false;
            // 
            // labelStatus
            // 
            this.labelStatus.AutoSize = true;
            this.labelStatus.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.labelStatus.Location = new System.Drawing.Point(316, 390);
            this.labelStatus.Name = "labelStatus";
            this.labelStatus.Size = new System.Drawing.Size(84, 20);
            this.labelStatus.TabIndex = 13;
            this.labelStatus.Text = "Status: ----";
            this.labelStatus.Visible = false;
            // 
            // buttonRestart
            // 
            this.buttonRestart.Location = new System.Drawing.Point(333, 413);
            this.buttonRestart.Name = "buttonRestart";
            this.buttonRestart.Size = new System.Drawing.Size(95, 23);
            this.buttonRestart.TabIndex = 6;
            this.buttonRestart.Text = "Play again";
            this.buttonRestart.UseVisualStyleBackColor = true;
            this.buttonRestart.Visible = false;
            this.buttonRestart.Click += new System.EventHandler(this.ButtonRestart_Click);
            // 
            // labelComputerMove
            // 
            this.labelComputerMove.AutoSize = true;
            this.labelComputerMove.ForeColor = System.Drawing.Color.Red;
            this.labelComputerMove.Location = new System.Drawing.Point(154, 390);
            this.labelComputerMove.Name = "labelComputerMove";
            this.labelComputerMove.Size = new System.Drawing.Size(80, 13);
            this.labelComputerMove.TabIndex = 18;
            this.labelComputerMove.Text = "Computer\'s turn";
            this.labelComputerMove.Visible = false;
            this.labelComputerMove.VisibleChanged += new System.EventHandler(this.LabelComputerMove_VisibleChanged);
            // 
            // label1x
            // 
            this.label1x.AutoSize = true;
            this.label1x.Location = new System.Drawing.Point(638, 102);
            this.label1x.Name = "label1x";
            this.label1x.Size = new System.Drawing.Size(13, 13);
            this.label1x.TabIndex = 17;
            this.label1x.Text = "4";
            // 
            // contextMenuStrip
            // 
            this.contextMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.GameRestartToolStripMenuItem,
            this.ComputerMovesSpeedToolStripMenuItem,
            this.MarkComputerMovesToolStripMenuItem});
            this.contextMenuStrip.Name = "contextMenuStrip";
            this.contextMenuStrip.Size = new System.Drawing.Size(201, 70);
            this.contextMenuStrip.Opening += new System.ComponentModel.CancelEventHandler(this.ContextMenuStrip_Opening);
            // 
            // GameRestartToolStripMenuItem
            // 
            this.GameRestartToolStripMenuItem.Name = "GameRestartToolStripMenuItem";
            this.GameRestartToolStripMenuItem.Size = new System.Drawing.Size(200, 22);
            this.GameRestartToolStripMenuItem.Text = "Restart Game";
            this.GameRestartToolStripMenuItem.Click += new System.EventHandler(this.GameRestartToolStripMenuItem_Click);
            // 
            // ComputerMovesSpeedToolStripMenuItem
            // 
            this.ComputerMovesSpeedToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.SlowlyToolStripMenuItem,
            this.AverageToolStripMenuItem,
            this.RapidlyToolStripMenuItem,
            this.InstantlyToolStripMenuItem});
            this.ComputerMovesSpeedToolStripMenuItem.Name = "ComputerMovesSpeedToolStripMenuItem";
            this.ComputerMovesSpeedToolStripMenuItem.Size = new System.Drawing.Size(200, 22);
            this.ComputerMovesSpeedToolStripMenuItem.Text = "Computer moves speed";
            // 
            // SlowlyToolStripMenuItem
            // 
            this.SlowlyToolStripMenuItem.Name = "SlowlyToolStripMenuItem";
            this.SlowlyToolStripMenuItem.Size = new System.Drawing.Size(119, 22);
            this.SlowlyToolStripMenuItem.Text = "Slowly";
            // 
            // AverageToolStripMenuItem
            // 
            this.AverageToolStripMenuItem.Checked = true;
            this.AverageToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.AverageToolStripMenuItem.Name = "AverageToolStripMenuItem";
            this.AverageToolStripMenuItem.Size = new System.Drawing.Size(119, 22);
            this.AverageToolStripMenuItem.Text = "Medium";
            // 
            // RapidlyToolStripMenuItem
            // 
            this.RapidlyToolStripMenuItem.Name = "RapidlyToolStripMenuItem";
            this.RapidlyToolStripMenuItem.Size = new System.Drawing.Size(119, 22);
            this.RapidlyToolStripMenuItem.Text = "Fast";
            // 
            // InstantlyToolStripMenuItem
            // 
            this.InstantlyToolStripMenuItem.Name = "InstantlyToolStripMenuItem";
            this.InstantlyToolStripMenuItem.Size = new System.Drawing.Size(119, 22);
            this.InstantlyToolStripMenuItem.Text = "Instantly";
            // 
            // MarkComputerMovesToolStripMenuItem
            // 
            this.MarkComputerMovesToolStripMenuItem.Checked = true;
            this.MarkComputerMovesToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.MarkComputerMovesToolStripMenuItem.Name = "MarkComputerMovesToolStripMenuItem";
            this.MarkComputerMovesToolStripMenuItem.Size = new System.Drawing.Size(200, 22);
            this.MarkComputerMovesToolStripMenuItem.Text = "Mark computer moves";
            this.MarkComputerMovesToolStripMenuItem.Click += new System.EventHandler(this.MarkComputerMovesToolStripMenuItem_Click);
            // 
            // buttonRotate
            // 
            this.buttonRotate.Location = new System.Drawing.Point(112, 110);
            this.buttonRotate.Name = "buttonRotate";
            this.buttonRotate.Size = new System.Drawing.Size(135, 23);
            this.buttonRotate.TabIndex = 4;
            this.buttonRotate.Text = "Rotate ship";
            this.buttonRotate.UseVisualStyleBackColor = true;
            this.buttonRotate.Click += new System.EventHandler(this.ButtonRotate_Click);
            // 
            // comboBoxComputerMoveSpeed
            // 
            this.comboBoxComputerMoveSpeed.FormattingEnabled = true;
            this.comboBoxComputerMoveSpeed.Items.AddRange(new object[] {
            "Slowly",
            "Medium",
            "Fast",
            "Instantly"});
            this.comboBoxComputerMoveSpeed.Location = new System.Drawing.Point(35, 42);
            this.comboBoxComputerMoveSpeed.Name = "comboBoxComputerMoveSpeed";
            this.comboBoxComputerMoveSpeed.Size = new System.Drawing.Size(135, 21);
            this.comboBoxComputerMoveSpeed.TabIndex = 15;
            this.comboBoxComputerMoveSpeed.SelectedIndexChanged += new System.EventHandler(this.ComboBox_SelectedIndexChanged);
            // 
            // buttonGameStart
            // 
            this.buttonGameStart.Enabled = false;
            this.buttonGameStart.Location = new System.Drawing.Point(112, 362);
            this.buttonGameStart.Name = "buttonGameStart";
            this.buttonGameStart.Size = new System.Drawing.Size(135, 23);
            this.buttonGameStart.TabIndex = 5;
            this.buttonGameStart.Text = "Start Game";
            this.buttonGameStart.UseVisualStyleBackColor = true;
            this.buttonGameStart.Click += new System.EventHandler(this.ButtonGameStart_Click);
            // 
            // labelShipsPlaceLeft
            // 
            this.labelShipsPlaceLeft.AutoSize = true;
            this.labelShipsPlaceLeft.BackColor = System.Drawing.Color.Transparent;
            this.labelShipsPlaceLeft.Location = new System.Drawing.Point(168, 383);
            this.labelShipsPlaceLeft.Name = "labelShipsPlaceLeft";
            this.labelShipsPlaceLeft.Size = new System.Drawing.Size(54, 13);
            this.labelShipsPlaceLeft.TabIndex = 14;
            this.labelShipsPlaceLeft.Text = "Ships Left";
            // 
            // labelPlaceShips
            // 
            this.labelPlaceShips.AutoSize = true;
            this.labelPlaceShips.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.labelPlaceShips.Location = new System.Drawing.Point(129, 10);
            this.labelPlaceShips.Name = "labelPlaceShips";
            this.labelPlaceShips.Size = new System.Drawing.Size(89, 20);
            this.labelPlaceShips.TabIndex = 15;
            this.labelPlaceShips.Text = "Place ships";
            // 
            // progressBar
            // 
            this.progressBar.Location = new System.Drawing.Point(94, 399);
            this.progressBar.Name = "progressBar";
            this.progressBar.Size = new System.Drawing.Size(206, 23);
            this.progressBar.TabIndex = 11;
            // 
            // labelComputerMovingSpeed
            // 
            this.labelComputerMovingSpeed.AutoSize = true;
            this.labelComputerMovingSpeed.Location = new System.Drawing.Point(67, 26);
            this.labelComputerMovingSpeed.Name = "labelComputerMovingSpeed";
            this.labelComputerMovingSpeed.Size = new System.Drawing.Size(66, 13);
            this.labelComputerMovingSpeed.TabIndex = 16;
            this.labelComputerMovingSpeed.Text = "Move speed";
            // 
            // labelShipPlacement
            // 
            this.labelShipPlacement.AutoSize = true;
            this.labelShipPlacement.Location = new System.Drawing.Point(143, 136);
            this.labelShipPlacement.Name = "labelShipPlacement";
            this.labelShipPlacement.Size = new System.Drawing.Size(65, 13);
            this.labelShipPlacement.TabIndex = 18;
            this.labelShipPlacement.Text = "Placement: |";
            // 
            // checkBoxMarkEnemyMoves
            // 
            this.checkBoxMarkEnemyMoves.AutoSize = true;
            this.checkBoxMarkEnemyMoves.Checked = true;
            this.checkBoxMarkEnemyMoves.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBoxMarkEnemyMoves.Location = new System.Drawing.Point(63, 80);
            this.checkBoxMarkEnemyMoves.Name = "checkBoxMarkEnemyMoves";
            this.checkBoxMarkEnemyMoves.Size = new System.Drawing.Size(84, 17);
            this.checkBoxMarkEnemyMoves.TabIndex = 19;
            this.checkBoxMarkEnemyMoves.Text = "Mark moves";
            this.checkBoxMarkEnemyMoves.UseVisualStyleBackColor = true;
            this.checkBoxMarkEnemyMoves.CheckedChanged += new System.EventHandler(this.CheckBoxMarkEnemyMoves_CheckedChanged);
            // 
            // panel
            // 
            this.panel.Controls.Add(this.groupBoxEnemy);
            this.panel.Controls.Add(this.buttonArrangeShipsRandomly);
            this.panel.Controls.Add(this.labelShipPlacement);
            this.panel.Controls.Add(this.labelPlaceShips);
            this.panel.Controls.Add(this.buttonGameStart);
            this.panel.Controls.Add(this.buttonRotate);
            this.panel.Location = new System.Drawing.Point(391, 25);
            this.panel.Name = "panel";
            this.panel.Size = new System.Drawing.Size(351, 397);
            this.panel.TabIndex = 19;
            // 
            // groupBoxEnemy
            // 
            this.groupBoxEnemy.Controls.Add(this.checkBoxMarkEnemyMoves);
            this.groupBoxEnemy.Controls.Add(this.checkBoxEnemyRandomMoves);
            this.groupBoxEnemy.Controls.Add(this.labelComputerMovingSpeed);
            this.groupBoxEnemy.Controls.Add(this.comboBoxComputerMoveSpeed);
            this.groupBoxEnemy.Location = new System.Drawing.Point(77, 217);
            this.groupBoxEnemy.Name = "groupBoxEnemy";
            this.groupBoxEnemy.Size = new System.Drawing.Size(200, 126);
            this.groupBoxEnemy.TabIndex = 21;
            this.groupBoxEnemy.TabStop = false;
            this.groupBoxEnemy.Text = "Enemy computer";
            // 
            // checkBoxEnemyRandomMoves
            // 
            this.checkBoxEnemyRandomMoves.AutoSize = true;
            this.checkBoxEnemyRandomMoves.Location = new System.Drawing.Point(56, 103);
            this.checkBoxEnemyRandomMoves.Name = "checkBoxEnemyRandomMoves";
            this.checkBoxEnemyRandomMoves.Size = new System.Drawing.Size(100, 17);
            this.checkBoxEnemyRandomMoves.TabIndex = 20;
            this.checkBoxEnemyRandomMoves.Text = "Random moves";
            this.checkBoxEnemyRandomMoves.UseVisualStyleBackColor = true;
            this.checkBoxEnemyRandomMoves.CheckedChanged += new System.EventHandler(this.CheckBoxEnemyRandomMoves_CheckedChanged);
            // 
            // buttonArrangeShipsRandomly
            // 
            this.buttonArrangeShipsRandomly.Location = new System.Drawing.Point(112, 168);
            this.buttonArrangeShipsRandomly.Name = "buttonArrangeShipsRandomly";
            this.buttonArrangeShipsRandomly.Size = new System.Drawing.Size(135, 23);
            this.buttonArrangeShipsRandomly.TabIndex = 22;
            this.buttonArrangeShipsRandomly.Text = "Arrange ships randomly";
            this.buttonArrangeShipsRandomly.UseVisualStyleBackColor = true;
            this.buttonArrangeShipsRandomly.Click += new System.EventHandler(this.ButtonArrangeShipsRandomly_Click);
            // 
            // labelPrompt
            // 
            this.labelPrompt.AutoSize = true;
            this.labelPrompt.BackColor = System.Drawing.SystemColors.Control;
            this.labelPrompt.ForeColor = System.Drawing.SystemColors.ControlDark;
            this.labelPrompt.Location = new System.Drawing.Point(638, 436);
            this.labelPrompt.Name = "labelPrompt";
            this.labelPrompt.Size = new System.Drawing.Size(142, 13);
            this.labelPrompt.TabIndex = 20;
            this.labelPrompt.Text = "right-click to change settings";
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(780, 449);
            this.ContextMenuStrip = this.contextMenuStrip;
            this.Controls.Add(this.labelPrompt);
            this.Controls.Add(this.label1x);
            this.Controls.Add(this.labelComputerMove);
            this.Controls.Add(this.labelShipsPlaceLeft);
            this.Controls.Add(this.buttonRestart);
            this.Controls.Add(this.labelStatus);
            this.Controls.Add(this.labelEnemyField);
            this.Controls.Add(this.progressBar);
            this.Controls.Add(this.labelYourField);
            this.Controls.Add(this.label4x);
            this.Controls.Add(this.label3x);
            this.Controls.Add(this.label2x);
            this.Controls.Add(this.button1x);
            this.Controls.Add(this.button2x);
            this.Controls.Add(this.button3x);
            this.Controls.Add(this.button4x);
            this.Controls.Add(this.panel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Sea battle";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.contextMenuStrip.ResumeLayout(false);
            this.panel.ResumeLayout(false);
            this.panel.PerformLayout();
            this.groupBoxEnemy.ResumeLayout(false);
            this.groupBoxEnemy.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button button4x;
        private System.Windows.Forms.Button button3x;
        private System.Windows.Forms.Button button2x;
        private System.Windows.Forms.Button button1x;
        private System.Windows.Forms.Label label2x;
        private System.Windows.Forms.Label label3x;
        private System.Windows.Forms.Label label4x;
        private System.Windows.Forms.Label labelYourField;
        private System.Windows.Forms.Label labelEnemyField;
        private System.Windows.Forms.Label labelStatus;
        private System.Windows.Forms.Button buttonRestart;
        private System.Windows.Forms.Label labelComputerMove;
        private System.Windows.Forms.Label label1x;
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem GameRestartToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ComputerMovesSpeedToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem SlowlyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem AverageToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem RapidlyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem InstantlyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem MarkComputerMovesToolStripMenuItem;
        private System.Windows.Forms.Button buttonRotate;
        private System.Windows.Forms.ComboBox comboBoxComputerMoveSpeed;
        private System.Windows.Forms.Button buttonGameStart;
        private System.Windows.Forms.Label labelShipsPlaceLeft;
        private System.Windows.Forms.Label labelPlaceShips;
        private System.Windows.Forms.ProgressBar progressBar;
        private System.Windows.Forms.Label labelComputerMovingSpeed;
        private System.Windows.Forms.Label labelShipPlacement;
        private System.Windows.Forms.CheckBox checkBoxMarkEnemyMoves;
        private System.Windows.Forms.Panel panel;
        private System.Windows.Forms.CheckBox checkBoxEnemyRandomMoves;
        private System.Windows.Forms.GroupBox groupBoxEnemy;
        private System.Windows.Forms.Button buttonArrangeShipsRandomly;
        private System.Windows.Forms.Label labelPrompt;
    }
}